const defaults: Record<string, string> = {
	PORT: "3000",
	MONGODB_URI: "mongodb://localhost:27017/test",
	REDIS_URI: "redis://localhost:6379",
	APP_URL: "http://localhost:3000",
	CLIENT_URL: "http://localhost:5173",
	NODE_ENV: "test",
	LOG_LEVEL: "error",
	LOKI_HOST: "http://localhost:3100",
	LOKI_USER: "test-user",
	LOKI_PASSWORD: "test-password",
	JWT_ACCESS_SECRET: "test-access-secret",
	JWT_REFRESH_SECRET: "test-refresh-secret",
	JWT_RESET_SECRET: "test-reset-secret",
	JWT_SETUP_SECRET: "test-setup-secret",
	CSRF_SECRET: "test-csrf-secret",
	SMTP_HOST: "localhost",
	SMTP_PORT: "1025",
	SMTP_USER: "test-smtp-user",
	SMTP_PASS: "test-smtp-pass",
	AWS_BUCKET_NAME: "test-bucket",
	AWS_ACCESS_KEY_ID: "test-access-key",
	AWS_SECRET_ACCESS_KEY: "test-secret-key",
	AWS_REGION: "ap-south-1",
	GOOGLE_CLIENT_ID: "test-google-client-id",
	GOOGLE_CLIENT_SECRET: "test-google-client-secret",
	LINKEDIN_CLIENT_ID: "test-linkedin-client-id",
	LINKEDIN_CLIENT_SECRET: "test-linkedin-client-secret",
	STRIPE_SECRET_KEY: "test-stripe-secret-key",
	STRIPE_WEBHOOK_SECRET: "test-stripe-webhook-secret",
	STRIPE_SUCCESS_URL: "http://localhost:5173/success",
	STRIPE_CANCEL_URL: "http://localhost:5173/cancel",
	VAPID_PRIVATE_KEY: "test-vapid-private-key",
	VAPID_PUBLIC_KEY: "test-vapid-public-key",
	DUMMY_LOGIN_EMAIL: "dummy@example.com",
};

for (const [key, value] of Object.entries(defaults)) {
	process.env[key] ??= value;
}
